import { z } from "zod";
import { money, uuid } from "./common.js";
import { invoiceStatus, taskKind, timeEntrySource } from "./enums.js";

// ── DTOs ─────────────────────────────────────────────────────────────────────

export const taskColumnSchema = z.object({
  id: uuid,
  name: z.string().min(1),
  order: z.number().int(),
  /** the "New" column — non-editable/deletable, default entry point */
  isFixed: z.boolean(),
});
export type TaskColumn = z.infer<typeof taskColumnSchema>;

export const subtaskSchema = z.object({
  id: uuid,
  taskId: uuid,
  text: z.string().min(1),
  done: z.boolean(),
  order: z.number().int(),
});
export type Subtask = z.infer<typeof subtaskSchema>;

/** One tracked interval (S6 redesign); stoppedAt null = the timer is running now. */
export const timeEntrySchema = z.object({
  id: uuid,
  taskId: uuid,
  userId: uuid,
  startedAt: z.iso.datetime(),
  stoppedAt: z.iso.datetime().nullable(),
  seconds: z.number().int().nullable(),
  comment: z.string().nullable(),
  source: timeEntrySource,
  /** admin who added a manual entry; null = the user's own timer */
  createdById: uuid.nullable(),
});
export type TimeEntry = z.infer<typeof timeEntrySchema>;

/** A free-text note on a task (for self or colleagues) — separate from the time-entry comment. */
export const taskCommentSchema = z.object({
  id: uuid,
  taskId: uuid,
  authorId: uuid,
  body: z.string(),
  createdAt: z.iso.datetime(),
});
export type TaskComment = z.infer<typeof taskCommentSchema>;

export const taskSchema = z.object({
  id: uuid,
  title: z.string().min(1),
  clientId: uuid.nullable(),
  companyId: uuid.nullable(),
  leadId: uuid.nullable(),
  serviceId: uuid.nullable(),
  /** once = billable one-off · sub = generated from a subscription · free = internal */
  kind: taskKind,
  priorityId: uuid,
  statusColumnId: uuid,
  /** independent completion flag — columns are pure workflow */
  done: z.boolean(),
  deadline: z.iso.datetime().nullable(),
  plannedMinutes: z.number().int().nonnegative().nullable(),
  /** one-off price (minor units) → invoice at S7; kind=once only */
  amount: money.nullable(),
  invoiceId: uuid.nullable(),
  description: z.string().nullable(),
  /** generation provenance (kind=sub) */
  subscriptionId: uuid.nullable(),
  taskTemplateId: uuid.nullable(),
  periodKey: z.string().nullable(),
  /** who created it; null = auto-generated by the scheduler */
  createdById: uuid.nullable(),
  /** target labels, resolved server-side (the board must not depend on a clients page) */
  clientName: z.string().nullable(),
  companyName: z.string().nullable(),
  leadName: z.string().nullable(),
  /**
   * The invoice issued for this job (one-time services; created per the service trigger),
   * including how much of it is settled — a task carries its own billing state so nobody has
   * to open Billing to see whether the work has been paid for.
   */
  invoice: z
    .object({
      id: uuid,
      number: z.string(),
      amount: money,
      paid: money,
      balance: money,
      status: invoiceStatus,
      /** null = created but not handed to the client yet */
      sentAt: z.iso.datetime().nullable(),
      issuedAt: z.iso.datetime(),
      dueDate: z.iso.datetime().nullable(),
    })
    .nullable(),
  assignees: z.array(uuid),
  subtasks: z.array(subtaskSchema),
  timeEntries: z.array(timeEntrySchema),
  comments: z.array(taskCommentSchema),
  /** Σ seconds of CLOSED intervals (a running one adds live elapsed client-side) */
  trackedSeconds: z.number().int(),
  createdAt: z.iso.datetime(),
  /** when it was marked done (null while open) — what the Done view's date window filters on */
  completedAt: z.iso.datetime().nullable(),
  /** raised by mistake or called off — the task leaves the board but is kept (2026-08-01) */
  cancelledAt: z.iso.datetime().nullable(),
  cancelledByName: z.string().nullable(),
  archivedAt: z.iso.datetime().nullable(),
});
export type Task = z.infer<typeof taskSchema>;

// `isTaskOverdue` lives in shared/dates.ts — it's a pure rule with no zod in it, and the
// frontend must be able to call it without pulling this schema module's runtime into the bundle.

// ── Task inputs ──────────────────────────────────────────────────────────────

const optionalText = z
  .string()
  .transform((v) => v.trim() || null)
  .nullable()
  .optional();

const workflowFields = z.object({
  title: z.string().trim().min(1).max(200),
  /** omitted → the default priority (Normal) */
  priorityId: uuid.optional(),
  /** omitted → the fixed "New" column */
  statusColumnId: uuid.optional(),
  deadline: z.iso.date().nullable().optional(),
  plannedMinutes: z.number().int().min(1).max(60_000).nullable().optional(),
  description: optionalText,
  assignees: z.array(uuid).max(20).default([]),
});

/**
 * Task targeting (decision 2026-07-23): a CLIENT task always goes through one
 * of the client's subscriptions — one-time service → billable job (price +
 * invoice per the service trigger), subscription service → free extra work
 * included in the price. A LEAD task is always free (no services yet).
 * Neither → internal. `kind`, service and company are DERIVED server-side.
 */
export const createTaskInput = workflowFields
  .extend({
    clientId: uuid.nullable().optional(),
    /** required with clientId — the client's subscription the work goes through */
    subscriptionId: uuid.nullable().optional(),
    leadId: uuid.nullable().optional(),
    /**
     * Firm-side work, not work sold to anyone. A client or lead may still be named — that is
     * ATTRIBUTION, not belonging: organising a client's paperwork is time spent on them and should
     * show up on their card, but it goes through no service, bills nothing and is never "included
     * in their plan" (user, 2026-08-01).
     */
    internal: z.boolean().optional(),
    /** one-time jobs only; omitted → the subscription's default job price */
    amount: money.nullable().optional(),
    /** initial checklist steps (e.g. prefilled from the picked template's default) */
    subtasks: z.array(z.string().trim().min(1).max(200)).max(50).optional(),
  })
  .refine((v) => !(v.clientId && v.leadId), {
    path: ["leadId"],
    message: "Pick a client or a lead, not both",
  })
  .refine((v) => v.internal || !v.clientId || !!v.subscriptionId, {
    path: ["subscriptionId"],
    message: "A client task goes through one of the client's services",
  })
  .refine((v) => !(v.internal && v.subscriptionId), {
    path: ["subscriptionId"],
    message: "Internal work goes through no service — it is the firm's own time",
  });
// assignees are optional (default = the creator in the UI; may be left empty)
export type CreateTaskInput = z.infer<typeof createTaskInput>;

/** Re-targeting isn't supported — create a new task instead (workflow fields only). */
export const updateTaskInput = workflowFields.partial().extend({
  done: z.boolean().optional(),
  /** call the task off (or take it back) — stamps who and when, exactly like `done` */
  cancelled: z.boolean().optional(),
  /** one-time jobs only, until invoiced */
  amount: money.nullable().optional(),
  // optional on PATCH — omitting keeps current assignees; [] clears them
  assignees: z.array(uuid).max(20).optional(),
});
export type UpdateTaskInput = z.infer<typeof updateTaskInput>;

/** Full replace of the checklist (order = array index). */
export const setSubtasksInput = z.object({
  subtasks: z
    .array(z.object({ text: z.string().trim().min(1).max(300), done: z.boolean().default(false) }))
    .max(50),
});
export type SetSubtasksInput = z.infer<typeof setSubtasksInput>;

export const createTaskCommentInput = z.object({
  body: z.string().trim().min(1).max(4000),
});
export type CreateTaskCommentInput = z.infer<typeof createTaskCommentInput>;

export const taskListQuery = z.object({
  view: z.enum(["board", "table"]).default("board"),
  /** board + table: the board defaults to open work, "done" is its own view */
  status: z.enum(["all", "open", "done", "cancelled"]).default("all"),
  search: z.string().trim().optional(),
  assigneeId: uuid.optional(),
  clientId: uuid.optional(),
  leadId: uuid.optional(),
  /** only work whose deadline day has passed (open tasks) — the board's "Overdue" chip, in SQL */
  overdue: z
    .enum(["true", "false"])
    .optional()
    .transform((v) => v === "true"),
  /**
   * Done view only: how far back to look, in whole days (7 = today plus the six before it).
   * Omitted = every completed task ever, which is what the screen must not default to.
   */
  doneWithinDays: z.coerce.number().int().min(1).max(3650).optional(),
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(50),
});
export type TaskListQuery = z.infer<typeof taskListQuery>;

// ── Columns ──────────────────────────────────────────────────────────────────

export const createColumnInput = z.object({ name: z.string().trim().min(1).max(40) });
export type CreateColumnInput = z.infer<typeof createColumnInput>;

export const updateColumnInput = z.object({
  name: z.string().trim().min(1).max(40).optional(),
  order: z.number().int().min(0).optional(),
});
export type UpdateColumnInput = z.infer<typeof updateColumnInput>;

// ── Timer ────────────────────────────────────────────────────────────────────

/**
 * One running timer per user. Starting while another runs: without
 * `closeComment` → 409 with the running entry (UI opens the comment modal);
 * with it → the old interval closes with that comment and the new one starts
 * atomically.
 */
export const startTimerInput = z.object({
  taskId: uuid,
  closeComment: z.string().trim().min(1).max(500).optional(),
});
export type StartTimerInput = z.infer<typeof startTimerInput>;

/** Every stop requires a comment — an interval never closes silently. */
export const stopTimerInput = z.object({
  comment: z.string().trim().min(1).max(500),
});
export type StopTimerInput = z.infer<typeof stopTimerInput>;

// ── Admin time management ────────────────────────────────────────────────────

export const addTimeEntryInput = z.object({
  userId: uuid,
  minutes: z.number().int().min(1).max(24 * 60),
  comment: z.string().trim().min(1).max(500),
  /** anchor date (defaults to now) */
  date: z.iso.date().optional(),
});
export type AddTimeEntryInput = z.infer<typeof addTimeEntryInput>;

export const updateTimeEntryInput = z
  .object({
    minutes: z.number().int().min(1).max(24 * 60).optional(),
    comment: z.string().trim().min(1).max(500).optional(),
  })
  .refine((v) => v.minutes !== undefined || v.comment !== undefined, {
    message: "Nothing to update",
  });
export type UpdateTimeEntryInput = z.infer<typeof updateTimeEntryInput>;
