import { config } from "../../core/config.js";
import type { Prisma } from "../../generated/prisma/client.js";
import * as repo from "./payments.repository.js";

/**
 * Invoice issuing — the single place a `number` is allocated and an Invoice row is
 * written (manual issue, one-time job billing from Tasks, per-period sweep).
 *
 * Numbering (decision 2026-07-17): PREFIX-YEAR-NNNN, counter resets yearly.
 * S6 derived the next counter from COUNT(*) of that year's invoices, which races
 * and re-uses a number once one is cancelled. S7 allocates it from a persisted
 * counter on FirmProfile, inside the same transaction as the insert — concurrent
 * issues serialize on that row and a failed insert rolls the counter back.
 * (Truly gapless numbering — the legal variant — stays deferred: a rolled-back
 * transaction is the only gap source left and it's rare.)
 */

/** The firm-timezone year — numbering resets on the firm's new year, not UTC's. */
export function firmYear(now: Date = new Date()): number {
  const s = new Intl.DateTimeFormat("en-CA", { timeZone: config.TZ }).format(now);
  return Number(s.slice(0, 4));
}

export interface IssueInvoiceInput {
  clientId: string;
  companyId: string | null;
  serviceId: string | null;
  subscriptionId?: string | null;
  /** set for per-period invoices — unique with subscriptionId (idempotency key) */
  periodKey?: string | null;
  description?: string | null;
  amount: number;
  /** business date the invoice is issued on; defaults to now */
  issuedAt?: Date;
  /** overdue terms: dueDate = issuedAt + dueDays. Ignored when `dueDate` is given. */
  dueDays?: number | null;
  dueDate?: Date | null;
  /** the user who issued it; null = generated by a job */
  createdById?: string | null;
  /** link an already-created task (one-time job billing) */
  taskId?: string | null;
}

const isUniqueOn = (err: unknown, field: string) =>
  (err as { code?: string }).code === "P2002" &&
  ((err as { meta?: { target?: unknown } }).meta?.target as string[] | undefined)?.includes(field) ===
    true;

/** The row to write, with the due date resolved from either an explicit date or `dueDays`. */
function invoiceRow(input: IssueInvoiceInput) {
  const issuedAt = input.issuedAt ?? new Date();
  const dueDate =
    input.dueDate !== undefined
      ? input.dueDate
      : input.dueDays != null
        ? new Date(issuedAt.getTime() + input.dueDays * 86_400_000)
        : null;
  const data: Omit<Prisma.InvoiceUncheckedCreateInput, "number"> = {
    clientId: input.clientId,
    companyId: input.companyId,
    serviceId: input.serviceId,
    subscriptionId: input.subscriptionId ?? null,
    periodKey: input.periodKey ?? null,
    description: input.description ?? null,
    amount: input.amount,
    issuedAt,
    dueDate,
    createdById: input.createdById ?? null,
  };
  return { data, year: firmYear(issuedAt) };
}

/**
 * Issue one invoice. Retries only on a `number` collision (a legacy S6 number can
 * sit on a counter value we're about to hand out); any other unique violation —
 * notably (subscriptionId, periodKey) — is the caller's business and propagates.
 */
export async function issueInvoice(input: IssueInvoiceInput) {
  const { data, year } = invoiceRow(input);
  for (let attempt = 0; ; attempt++) {
    try {
      return await repo.inTransaction((tx) => repo.insertInvoice(tx, year, data, input.taskId));
    } catch (err) {
      if (attempt < 5 && isUniqueOn(err, "number")) continue; // burnt number → take the next one
      throw err;
    }
  }
}

/**
 * Issue inside a transaction the CALLER already opened — used when the decision to bill and the
 * billing itself have to be one atomic step (a one-time job's invoice is issued under the task's
 * row lock). No retry loop here: a failed insert has to abort the caller's transaction, and the
 * `number` collision it would retry can only come from pre-S7 rows the counter has long passed.
 */
export function issueInvoiceIn(tx: Prisma.TransactionClient, input: IssueInvoiceInput) {
  const { data, year } = invoiceRow(input);
  return repo.insertInvoice(tx, year, data, input.taskId);
}

export interface JobInvoiceInput {
  taskId: string;
  clientId: string;
  companyId: string | null;
  serviceId: string | null;
  amount: number;
  /** service.dueDays (per-client override wins) — invoice overdue after N days */
  dueDays: number | null;
  createdById?: string | null;
}

/**
 * One-time job billing (S6 entry point, kept as its own name so Tasks reads clearly).
 *
 * The task's row is locked FIRST and its `invoiceId` re-read inside the transaction: two people
 * marking the same job done at the same moment would otherwise both see "not billed yet" and the
 * client would get two invoices for one job. Returns null when someone else already billed it.
 */
export function issueJobInvoice(input: JobInvoiceInput) {
  return repo.inTransaction(async (tx) => {
    const task = await repo.lockTaskForInvoicing(tx, input.taskId);
    if (task.invoiceId) return null; // already billed — by us a moment ago, or by whoever raced us
    return issueInvoiceIn(tx, input);
  });
}
