import { config } from "../../core/config.js";
import { todayInTz, toUtc } from "../../core/dates.js";
import type { Prisma } from "../../generated/prisma/client.js";
import * as repo from "./payments.repository.js";

/**
 * Invoice issuing — the single place a `number` is allocated and an Invoice row is
 * written (manual issue, one-time job billing from Tasks, per-period sweep).
 *
 * Numbering (decision 2026-07-17): PREFIX-YEAR-NNNN, counter resets yearly.
 * S6 derived the next counter from COUNT(*) of that year's invoices, which races
 * and re-uses a number once one is cancelled. S7 allocates it from a persisted
 * counter on FirmProfile, inside the same transaction as the insert — concurrent
 * issues serialize on that row and a failed insert rolls the counter back.
 * (Truly gapless numbering — the legal variant — stays deferred: a rolled-back
 * transaction is the only gap source left and it's rare.)
 */

/**
 * The year an invoice's issue date falls in — numbering resets on the firm's new year. The issue
 * date is always a business date (UTC midnight of the firm's calendar day, see `invoiceRow`), so
 * its UTC year IS the firm's year; reading it back through `Intl` in the firm timezone would be
 * the same conversion twice, and wrong by a year on 1 January for a firm west of UTC.
 */
export function firmYear(issuedAt: Date): number {
  return issuedAt.getUTCFullYear();
}

export interface IssueInvoiceInput {
  clientId: string;
  companyId: string | null;
  serviceId: string | null;
  subscriptionId?: string | null;
  /** set for per-period invoices — unique with subscriptionId (idempotency key) */
  periodKey?: string | null;
  description?: string | null;
  amount: number;
  /** business date the invoice is issued on; defaults to now */
  issuedAt?: Date;
  /** overdue terms: dueDate = issuedAt + dueDays. Ignored when `dueDate` is given. */
  dueDays?: number | null;
  dueDate?: Date | null;
  /** the user who issued it; null = generated by a job */
  createdById?: string | null;
  /** link an already-created task (one-time job billing) */
  taskId?: string | null;
  /**
   * The breakdown, written in the SAME transaction as the invoice.
   *
   * `amount` above must already be their sum — the caller derives it, because the caller is the
   * one that decides whether positions or a typed number own the total. Writing them apart would
   * leave a moment where an invoice's amount and the rows it is made of disagree.
   */
  lines?: StoredLine[] | null;
}

export interface StoredLine {
  order: number;
  description: string;
  quantity: number | null;
  unitRate: number | null;
  amount: number;
}

const isUniqueOn = (err: unknown, field: string) =>
  (err as { code?: string }).code === "P2002" &&
  ((err as { meta?: { target?: unknown } }).meta?.target as string[] | undefined)?.includes(field) ===
    true;

/** The row to write, with the due date resolved from either an explicit date or `dueDays`. */
function invoiceRow(input: IssueInvoiceInput) {
  // an issue date is a BUSINESS DATE, not the instant of the click: stamped at UTC midnight of
  // the firm's day, exactly like the period sweep. Storing the raw instant made `issuedAt` and
  // its derived `dueDate` land mid-day, so they read a day early west of UTC (2026-07-27).
  const issuedAt = input.issuedAt ?? toUtc(todayInTz(config.TZ));
  const dueDate =
    input.dueDate !== undefined
      ? input.dueDate
      : input.dueDays != null
        ? new Date(issuedAt.getTime() + input.dueDays * 86_400_000)
        : null;
  const data: Omit<Prisma.InvoiceUncheckedCreateInput, "number"> = {
    clientId: input.clientId,
    companyId: input.companyId,
    serviceId: input.serviceId,
    subscriptionId: input.subscriptionId ?? null,
    periodKey: input.periodKey ?? null,
    description: input.description ?? null,
    amount: input.amount,
    issuedAt,
    dueDate,
    createdById: input.createdById ?? null,
  };
  return { data, year: firmYear(issuedAt) };
}

/**
 * Issue one invoice. Retries only on a `number` collision (a legacy S6 number can
 * sit on a counter value we're about to hand out); any other unique violation —
 * notably (subscriptionId, periodKey) — is the caller's business and propagates.
 */
export async function issueInvoice(input: IssueInvoiceInput) {
  const { data, year } = invoiceRow(input);
  for (let attempt = 0; ; attempt++) {
    try {
      return await repo.inTransaction(async (tx) => {
        const invoice = await repo.insertInvoice(tx, year, data, input.taskId);
        if (input.lines?.length) await repo.replaceLines(tx, invoice.id, input.lines);
        return invoice;
      });
    } catch (err) {
      if (attempt < 5 && isUniqueOn(err, "number")) continue; // burnt number → take the next one
      throw err;
    }
  }
}

/**
 * Issue inside a transaction the CALLER already opened — used when the decision to bill and the
 * billing itself have to be one atomic step (a one-time job's invoice is issued under the task's
 * row lock). No retry loop here: a failed insert has to abort the caller's transaction, and the
 * `number` collision it would retry can only come from pre-S7 rows the counter has long passed.
 */
export function issueInvoiceIn(tx: Prisma.TransactionClient, input: IssueInvoiceInput) {
  const { data, year } = invoiceRow(input);
  return repo.insertInvoice(tx, year, data, input.taskId);
}

export interface JobInvoiceInput {
  taskId: string;
  clientId: string;
  companyId: string | null;
  serviceId: string | null;
  amount: number;
  /** service.dueDays (per-client override wins) — invoice overdue after N days */
  dueDays: number | null;
  createdById?: string | null;
}

/**
 * One-time job billing (S6 entry point, kept as its own name so Tasks reads clearly).
 *
 * The task's row is locked FIRST and its `invoiceId` re-read inside the transaction: two people
 * marking the same job done at the same moment would otherwise both see "not billed yet" and the
 * client would get two invoices for one job. Returns null when someone else already billed it.
 *
 * "Already billed" means billed by an invoice that STILL COUNTS. A cancelled one is void — it owes
 * nothing, it is out of the debt and the unpaid list — and treating it as a bill left the job
 * permanently unbillable: this guard refused it, and a cancelled invoice cannot be edited either,
 * so the work was stranded between the two. Voiding the paper must not void the job.
 *
 * The link itself is left alone on cancel, so a voided invoice can still say what it was for; it
 * moves only when the job is genuinely billed again.
 */
export function issueJobInvoice(input: JobInvoiceInput) {
  return repo.inTransaction(async (tx) => {
    const task = await repo.lockTaskForInvoicing(tx, input.taskId);
    if (task.invoiceId && !task.invoice?.cancelledAt) return null;
    return issueInvoiceIn(tx, input);
  });
}
